server:
  port: 8080
  servlet:
    context-path: /api

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            trust: smtp.gmail.com
  config:
    import: optional:file:.env.local[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/pharmatel
    username: postgres
    password: 123far
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.security: INFO

app:
  cors:
    allowed-origins: "*"
  jwt:
    secret: 9f3c1a7b2c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0
    expiration-minutes: 120
